# Generated by Django 3.1 on 2020-09-05 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_toy_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='shareable',
            field=models.BooleanField(default=False),
        ),
    ]
